---
abstract: 'IRC client or server backend'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-IRC-Backend
recommends:
  POE::Component::SSLify: 1.006
  POE::Filter::Zlib::Stream: 0
requires:
  Carp: 0
  Exporter: 0
  IRC::Toolkit: 0
  Moo: 1
  MooX::Types::MooseLike: 0.15
  Net::IP::Minimal: 0.04
  POE: 1.3
  POE::Filter::IRCv3: 0
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Scalar::Util: 0
  Socket: 2
  Try::Tiny: 0
  namespace::clean: 0
  perl: v5.10.1
  strictures: 1
resources:
  repository: git://github.com/avenj/poex-irc-backend.git
version: 0.024003
